name: markdown_viewer
description: A simple Markdown viewer application.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_markdown: ^0.7.1
  file_picker: ^8.0.0
  url_launcher: ^6.2.0
  printing: ^5.11.0
  markdown: ^7.1.1
  pdf: ^3.10.0
  flex_color_scheme: ^8.4.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  shared_preferences: ^2.2.2
  window_manager: ^0.4.3
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  msix: ^3.16.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - logo/

msix_config:
  display_name: MarkPress
  publisher_display_name: Toulzac
  identity_name: Toulzac.MarkPress
  publisher: CN=B4FF146D-2F34-4659-A82D-63458E3B4CFB
  msix_version: 2.0.0.0
  logo_path: windows/runner/resources/app_icon.ico
  capabilities: internetClient
  languages: en-us, fr-fr, de-de, es-es, it-it
